package com.runetpisun.croverlay;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.Reader;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Card hitpoints and spell damage by level, loaded from assets/stats.tsv
 * (generated by tools/gen_stats.py). Pure Java so it is testable on the JVM.
 */
public final class Stats {
    public static final int MAX_LEVEL = 16;

    public static final class Unit {
        public final String label;
        public final int count;
        private final int[] hp;
        private final int[] shield;

        Unit(String label, int count, int[] hp, int[] shield) {
            this.label = label;
            this.count = count;
            this.hp = hp;
            this.shield = shield;
        }

        public int hp(int level) {
            return at(hp, level);
        }

        public int shield(int level) {
            return at(shield, level);
        }
    }

    public static final class Spell {
        public final int hits;
        public final int towerPercent;
        private final int[] damage;

        Spell(int hits, int[] damage, int towerPercent) {
            this.hits = hits;
            this.damage = damage;
            this.towerPercent = towerPercent;
        }

        /** Damage of one hit at the given card level (0 if unknown). */
        public int hitDamage(int level) {
            return at(damage, level);
        }

        public int totalDamage(int level) {
            return hitDamage(level) * hits;
        }

        public int towerDamage(int level) {
            return Math.round(totalDamage(level) * towerPercent / 100f);
        }

        /**
         * HP the unit has left after this spell (<= 0 means it dies). A shield absorbs a whole
         * hit and excess damage does not carry over, as in the game. Integer.MAX_VALUE if unknown.
         */
        public int hpLeft(int spellLevel, Unit unit, int unitLevel) {
            int dmg = hitDamage(spellLevel);
            int hp = unit.hp(unitLevel);
            if (dmg <= 0 || hp <= 0) return Integer.MAX_VALUE;
            int shield = unit.shield(unitLevel);
            for (int i = 0; i < hits && hp > 0; i++) {
                if (shield > 0) shield = Math.max(0, shield - dmg);
                else hp -= dmg;
            }
            return hp;
        }
    }

    private final Map<String, List<Unit>> units = new HashMap<>();
    private final Map<String, Spell> spells = new HashMap<>();

    public static Stats parse(Reader in) throws IOException {
        Stats s = new Stats();
        BufferedReader r = new BufferedReader(in);
        String line;
        while ((line = r.readLine()) != null) {
            if (line.isEmpty() || line.startsWith("#")) continue;
            String[] p = line.split("\t");
            if (p[0].equals("U") && p.length >= 6) {
                List<Unit> list = s.units.get(p[1]);
                if (list == null) s.units.put(p[1], list = new ArrayList<>());
                list.add(new Unit(p[2], Integer.parseInt(p[3]), ints(p[4]), ints(p[5])));
            } else if (p[0].equals("S") && p.length >= 5) {
                s.spells.put(p[1], new Spell(Integer.parseInt(p[2]), ints(p[3]), Integer.parseInt(p[4])));
            }
        }
        return s;
    }

    public List<Unit> units(Card card) {
        List<Unit> list = units.get(card.name);
        return list == null ? Collections.<Unit>emptyList() : list;
    }

    public Spell spell(Card card) {
        return spells.get(card.name);
    }

    private static int[] ints(String csv) {
        String[] parts = csv.split(",");
        int[] out = new int[parts.length];
        for (int i = 0; i < parts.length; i++) out[i] = Integer.parseInt(parts[i].trim());
        return out;
    }

    private static int at(int[] arr, int level) {
        int i = level - 1;
        return i >= 0 && i < arr.length ? arr[i] : 0;
    }
}
