#!/usr/bin/env python3
"""Generates app/src/main/assets/stats.tsv from RoyaleAPI cr-api-data JSON.

Usage: tools/gen_stats.py <dir with cards.json and cards_stats.json> <out.tsv>
Data: https://github.com/RoyaleAPI/cr-api-data (docs/json)

Rows (values indexed by card level 1..MAX_LEVEL, 0 = not available):
  U <card> <unit> <count> <hp,...> <shield,...>
  S <card> <hits> <damage per hit,...> <crown tower %>
"""
import json
import sys

MAX_LEVEL = 16
START = {"Common": 1, "Rare": 3, "Epic": 6, "Legendary": 9, "Champion": 11}

# Damaging spells: card sc_key -> (section, object name, field kind, hits)
SPELLS = {
    "Fireball": ("projectile", "FireballSpell", "proj", 1),
    "Arrows": ("projectile", "ArrowsSpell", "proj", 3),
    "Rocket": ("projectile", "RocketSpell", "proj", 1),
    "Lightning": ("projectile", "LighningSpell", "proj", 1),
    "Log": ("projectile", "LogProjectileRolling", "proj", 1),
    "BarbLog": ("projectile", "BarbLogProjectileRolling", "proj", 1),
    "Snowball": ("projectile", "SnowballSpell", "proj", 1),
    "RoyalDelivery": ("projectile", "RoyalDeliveryProjectile", "proj", 1),
    "Zap": ("spell", "Zap", "base", 1),
    "Poison": ("character_buff", "Poison", "dps", 8),
    "Earthquake": ("character_buff", "Earthquake", "dps", 3),
}


def main(src, out):
    stats = json.load(open(f"{src}/cards_stats.json"))
    cards = json.load(open(f"{src}/cards.json"))
    idx = {sec: {x.get("name"): x for x in rows} for sec, rows in stats.items()}
    # Level curve used to scale values that have only a base number (ratio per level step).
    ref = idx["projectile"]["FireballSpell"]["damage_per_level"]
    curve = [v / ref[0] for v in ref] + [ref[-1] / ref[0] * 1.1 ** k for k in range(1, 10)]

    def by_level(arr, rarity):
        out = [0] * MAX_LEVEL
        for i, v in enumerate(arr or []):
            lvl = START[rarity] + i
            if lvl <= MAX_LEVEL:
                out[lvl - 1] = int(v)
        return out

    def scaled(base, rarity):
        return by_level([round(base * c) for c in curve], rarity)

    def csv(vals):
        return ",".join(str(v) for v in vals)

    rows = []

    def unit(card_name, char_name, count):
        ch = idx["characters"].get(char_name) or idx["building"].get(char_name)
        if not ch or not ch.get("hitpoints"):
            return
        rarity = ch.get("rarity") or "Common"
        hp = by_level(ch.get("hitpoints_per_level"), rarity) if ch.get("hitpoints_per_level") \
            else scaled(ch["hitpoints"], rarity)
        shield = ch.get("shield_hitpoints") or 0
        sh = by_level(ch.get("shield_hitpoints_per_level"), rarity) if ch.get("shield_hitpoints_per_level") \
            else (scaled(shield, rarity) if shield else [0] * MAX_LEVEL)
        label = ch.get("name_en") or char_name
        rows.append(["U", card_name, label, str(max(1, count)), csv(hp), csv(sh)])

    for card in cards:
        name, key, rarity = card["name"], card["sc_key"], card["rarity"]
        if card["type"] == "Troop" and key in idx["troop"]:
            t = idx["troop"][key]
            if t.get("summon_character"):
                unit(name, t["summon_character"], t.get("summon_number") or 1)
            if t.get("summon_character_second"):
                unit(name, t["summon_character_second"], t.get("summon_character_second_count") or 1)
        elif card["type"] == "Building" and key in idx["building"]:
            unit(name, key, 1)
        elif card["type"] == "Spell" and key in SPELLS:
            sec, obj, kind, hits = SPELLS[key]
            o = idx[sec][obj]
            if kind == "proj":
                dmg = by_level(o["damage_per_level"], rarity)
            elif kind == "base":
                dmg = scaled(o["damage"], rarity)
            else:
                dmg = scaled(o["damage_per_second"], rarity)
            tower = 100 + (o.get("crown_tower_damage_percent") or 0)
            rows.append(["S", name, str(hits), csv(dmg), str(tower)])

    with open(out, "w") as f:
        f.write("# generated by tools/gen_stats.py from RoyaleAPI cr-api-data\n")
        for r in rows:
            f.write("\t".join(r) + "\n")
    print(f"{len(rows)} rows -> {out}")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
